# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('timestarted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
